
FROM apache/spark:3.5.5

USER root


RUN pip install --no-cache-dir \
    requests \
    pandas \
    "clickhouse-connect>=0.5.0,<0.6.0"  # диапазон, а не конкретная версия


RUN wget -P /opt/spark/jars/ \
    https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.4.6/clickhouse-jdbc-0.4.6-all.jar

USER spark